name: Clean JSON Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Allows manual trigger

jobs:
  clean-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: |
          rm -rf ${{ github.workspace }}/*

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil

      - name: Clean JSON data
        run: python clean_json.py

      - name: Check JSON validity
        run: |
          python -c "import json; json.load(open('data.json'))"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: clean JSON data [skip ci]" && git push)
