name: Clean Old Gossip Entries and Track Celebrities
on:
  schedule:
    - cron: '30 * * * *'  # Runs at 30 minutes past every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  cleanup-and-track:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Process Entries and Update Lists
        run: |
          node cleanup-script.js
        continue-on-error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-logs
          path: cleanup.log

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/gossip_data.json celebrities.txt
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update celebrity tracking and clean old entries"
            git push
          fi
