name: Update Gossip and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering
  push:
    branches: ["main"] # Also runs on pushes to main branch

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-gossip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser pytz python-dateutil
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run update script
      run: python scripts/update_gossip.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update gossip data" && git push)

  deploy-to-github-pages:
    needs: update-gossip
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Upload the entire repository
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
